export type ContractType = "Main Consultancy Agreement" | "Sub-Consultancy Agreement" | "Works Contract";
export type BillingStatus = "Unbilled" | "Invoiced" | "Paid";
export type VariationReason = "Scope Addition" | "Client Request" | "Unforeseen Site Condition";
export type VariationApproval = "Draft" | "Under Review" | "Approved" | "Rejected";
export interface VariationOrder { id: string; title: string; reason: VariationReason; costImpactUsd: number; timeImpactDays: number; status: VariationApproval; }
export interface PaymentMilestone { id: string; description: string; feePercentage: number; status: BillingStatus; dueDate: string; }
export interface Contract { id: string; title: string; project: string; client: string; type: ContractType; reference: string; currency: "USD"; originalPriceUsd: number; originalPriceEtb: number; disbursedUsd: number; originalCompletion: string; extensionDays: number; revisedCompletion: string; ldExposureUsd: number; variations: VariationOrder[]; milestones: PaymentMilestone[]; }

export const contracts: Contract[] = [
  { id: "CTR-2024-014", title: "Design Review & Construction Supervision Services", project: "Addis Ababa Civic Centre", client: "Ministry of Foreign Affairs", type: "Main Consultancy Agreement", reference: "MOFA/PMC/014/2024", originalPriceUsd: 2_150_000, originalPriceEtb: 298_850_000, disbursedUsd: 1_208_000, originalCompletion: "30 Nov 2026", extensionDays: 90, revisedCompletion: "28 Feb 2027", ldExposureUsd: 86_000, variations: [{ id: "VO-01", title: "Basement waterproofing supervision scope", reason: "Scope Addition", costImpactUsd: 135_000, timeImpactDays: 30, status: "Approved" }, { id: "VO-02", title: "Client-requested security systems coordination", reason: "Client Request", costImpactUsd: 72_000, timeImpactDays: 15, status: "Under Review" }], milestones: [{ id: "MS-1", description: "Mobilization and inception report", feePercentage: 10, status: "Paid", dueDate: "15 Jan 2025" }, { id: "MS-2", description: "Design review completion", feePercentage: 25, status: "Paid", dueDate: "30 Jun 2025" }, { id: "MS-3", description: "Construction supervision — 50% progress", feePercentage: 30, status: "Invoiced", dueDate: "15 Jul 2026" }, { id: "MS-4", description: "Practical completion and handover", feePercentage: 25, status: "Unbilled", dueDate: "30 Nov 2026" }, { id: "MS-5", description: "Defects liability closeout", feePercentage: 10, status: "Unbilled", dueDate: "28 Feb 2027" }] },
  { id: "CTR-2025-023", title: "FIDIC White Book Consultancy Contract", project: "Modjo Logistics Hub", client: "Oromia Regional Works Bureau", type: "Main Consultancy Agreement", reference: "ORWB/PMC/023/2025", originalPriceUsd: 1_780_000, originalPriceEtb: 247_420_000, disbursedUsd: 620_000, originalCompletion: "15 Mar 2027", extensionDays: 0, revisedCompletion: "15 Mar 2027", ldExposureUsd: 53_400, variations: [{ id: "VO-01", title: "Additional geotechnical investigation", reason: "Unforeseen Site Condition", costImpactUsd: 96_000, timeImpactDays: 21, status: "Approved" }], milestones: [{ id: "MS-1", description: "Project inception", feePercentage: 15, status: "Paid", dueDate: "01 Apr 2025" }, { id: "MS-2", description: "Detailed design deliverables", feePercentage: 30, status: "Invoiced", dueDate: "30 Sep 2025" }, { id: "MS-3", description: "Supervision services — interim", feePercentage: 35, status: "Unbilled", dueDate: "15 Sep 2026" }, { id: "MS-4", description: "Final completion report", feePercentage: 20, status: "Unbilled", dueDate: "15 Mar 2027" }] },
  { id: "SUB-2025-007", title: "Specialist Geotechnical Services Agreement", project: "Modjo Logistics Hub", client: "Nile Design & Survey Consultants", type: "Sub-Consultancy Agreement", reference: "SC/NDSC/MLH/007", originalPriceUsd: 184_000, originalPriceEtb: 25_576_000, disbursedUsd: 128_800, originalCompletion: "31 Oct 2026", extensionDays: 14, revisedCompletion: "14 Nov 2026", ldExposureUsd: 9_200, variations: [], milestones: [{ id: "MS-1", description: "Field investigation and borehole logs", feePercentage: 40, status: "Paid", dueDate: "30 Apr 2025" }, { id: "MS-2", description: "Draft geotechnical interpretive report", feePercentage: 35, status: "Paid", dueDate: "30 Jun 2025" }, { id: "MS-3", description: "Final report and design support", feePercentage: 25, status: "Unbilled", dueDate: "14 Nov 2026" }] },
  { id: "WRK-2025-002", title: "Road Improvement Works Contract Administration", project: "Hawassa Ring Road Package 2", client: "Rift Valley Engineering Contractors", type: "Works Contract", reference: "HRR/WKS/002/2025", originalPriceUsd: 4_600_000, originalPriceEtb: 639_400_000, disbursedUsd: 2_850_000, originalCompletion: "31 Dec 2026", extensionDays: 45, revisedCompletion: "14 Feb 2027", ldExposureUsd: 184_000, variations: [{ id: "VO-01", title: "Unforeseen utility relocation", reason: "Unforeseen Site Condition", costImpactUsd: 245_000, timeImpactDays: 45, status: "Approved" }, { id: "VO-02", title: "Additional road safety measures", reason: "Client Request", costImpactUsd: 48_000, timeImpactDays: 0, status: "Draft" }], milestones: [{ id: "MS-1", description: "Advance payment certification", feePercentage: 15, status: "Paid", dueDate: "15 Apr 2025" }, { id: "MS-2", description: "Interim payment certificate no. 8", feePercentage: 35, status: "Paid", dueDate: "30 Jun 2026" }, { id: "MS-3", description: "Interim payment certificate no. 9", feePercentage: 25, status: "Invoiced", dueDate: "31 Jul 2026" }, { id: "MS-4", description: "Taking-over certificate", feePercentage: 25, status: "Unbilled", dueDate: "14 Feb 2027" }] },
];

export function approvedVariationValue(contract: Contract): number { return contract.variations.filter((variation) => variation.status === "Approved").reduce((sum, variation) => sum + variation.costImpactUsd, 0); }
export function revisedContractValue(contract: Contract): number { return contract.originalPriceUsd + approvedVariationValue(contract); }
export function milestoneValue(contract: Contract, milestone: PaymentMilestone): number { return revisedContractValue(contract) * (milestone.feePercentage / 100); }
export function remainingUnbilled(contract: Contract): number { return contract.milestones.filter((milestone) => milestone.status === "Unbilled").reduce((sum, milestone) => sum + milestoneValue(contract, milestone), 0); }
export function formatContractCurrency(value: number, currency: "USD" | "ETB" = "USD"): string { return new Intl.NumberFormat("en-US", { style: "currency", currency, maximumFractionDigits: 0 }).format(value); }
export function contractMetrics() { const active = contracts; return { totalUsd: active.reduce((sum, contract) => sum + revisedContractValue(contract), 0), totalEtb: active.reduce((sum, contract) => sum + contract.originalPriceEtb, 0), approvedVos: active.reduce((sum, contract) => sum + approvedVariationValue(contract), 0), unbilled: active.reduce((sum, contract) => sum + remainingUnbilled(contract), 0), extensions: active.filter((contract) => contract.extensionDays > 0).length }; }
