export type TenderStage = "EOI" | "RFP Received" | "Technical Proposal" | "Financial Proposal" | "Under Evaluation" | "Awarded" | "Lost";
export type ClientType = "Public" | "Private" | "Donor-Funded";
export type ConsultancyType = "Design & Supervision" | "PMC" | "Feasibility Study";
export interface TenderPerson { name: string; role: string; expertise: string; manMonths: number; }
export interface TenderChecklist { item: string; complete: boolean; }
export interface Tender {
  id: string; title: string; client: string; clientType: ClientType; consultancyType: ConsultancyType; stage: TenderStage; location: string; reference: string; valueUsd: number; valueEtb: number; deadline: string; deadlineDays: number; probability: number;
  dates: { preBid: string; siteVisit: string; technicalOpening: string; financialOpening: string };
  personnel: TenderPerson[]; financial: { technicalWeight: number; financialWeight: number; ourPriceUsd: number; competitors: { bidder: string; priceUsd: number }[] }; checklist: TenderChecklist[];
}

export const tenderStages: TenderStage[] = ["EOI", "RFP Received", "Technical Proposal", "Financial Proposal", "Under Evaluation", "Awarded", "Lost"];
export const tenders: Tender[] = [
  { id: "TND-2026-021", title: "Regional Market Infrastructure Design & Supervision", client: "Oromia Regional Works Bureau", clientType: "Public", consultancyType: "Design & Supervision", stage: "Technical Proposal", location: "Adama & Shashemene", reference: "ORWB/RFP/021/2026", valueUsd: 1_450_000, valueEtb: 201_550_000, deadline: "29 Jul 2026", deadlineDays: 5, probability: 62, dates: { preBid: "18 Jul 2026", siteVisit: "20 Jul 2026", technicalOpening: "29 Jul 2026", financialOpening: "12 Aug 2026" }, personnel: [{ name: "Mekdes Asfaw", role: "Proposed Team Lead", expertise: "Infrastructure Delivery", manMonths: 18 }, { name: "Liya Mekonnen", role: "Key Expert", expertise: "Architectural Design", manMonths: 12 }, { name: "Solomon Ayele", role: "Key Expert", expertise: "Cost Engineering", manMonths: 8 }], financial: { technicalWeight: 80, financialWeight: 20, ourPriceUsd: 1_410_000, competitors: [{ bidder: "Nile Engineering Group", priceUsd: 1_380_000 }, { bidder: "Axis Consultants", priceUsd: 1_465_000 }] }, checklist: [{ item: "Bid bond", complete: true }, { item: "Compliance documents", complete: true }, { item: "Technical methodology", complete: false }, { item: "CVs and commitment letters", complete: true }] },
  { id: "TND-2026-018", title: "Ministry Headquarters Construction Supervision", client: "Ministry of Foreign Affairs", clientType: "Public", consultancyType: "PMC", stage: "Financial Proposal", location: "Addis Ababa", reference: "MOFA/PMC/018/2026", valueUsd: 2_800_000, valueEtb: 389_200_000, deadline: "02 Aug 2026", deadlineDays: 9, probability: 74, dates: { preBid: "15 Jul 2026", siteVisit: "17 Jul 2026", technicalOpening: "02 Aug 2026", financialOpening: "08 Aug 2026" }, personnel: [{ name: "Dawit Kebede", role: "Proposed Team Lead", expertise: "Project Management", manMonths: 24 }, { name: "Samuel Tadesse", role: "Key Expert", expertise: "Resident Supervision", manMonths: 30 }, { name: "Rahel Birhane", role: "Key Expert", expertise: "Contract Administration", manMonths: 10 }], financial: { technicalWeight: 70, financialWeight: 30, ourPriceUsd: 2_740_000, competitors: [{ bidder: "ProBuild Africa", priceUsd: 2_690_000 }, { bidder: "Ethiopian Engineering Corp.", priceUsd: 2_830_000 }] }, checklist: [{ item: "Bid bond", complete: true }, { item: "Compliance documents", complete: true }, { item: "Technical methodology", complete: true }, { item: "CVs and commitment letters", complete: true }] },
  { id: "TND-2026-014", title: "Urban Transport Master Plan & Feasibility", client: "Cities Alliance Ethiopia", clientType: "Donor-Funded", consultancyType: "Feasibility Study", stage: "Under Evaluation", location: "Dire Dawa", reference: "CAE/UTMP/014/2026", valueUsd: 980_000, valueEtb: 136_220_000, deadline: "Submitted", deadlineDays: 0, probability: 48, dates: { preBid: "21 May 2026", siteVisit: "26 May 2026", technicalOpening: "18 Jun 2026", financialOpening: "25 Jul 2026" }, personnel: [{ name: "Fikru Bekele", role: "Proposed Team Lead", expertise: "Transport Planning", manMonths: 16 }, { name: "Selam Hailu", role: "Key Expert", expertise: "Urban Economics", manMonths: 8 }], financial: { technicalWeight: 75, financialWeight: 25, ourPriceUsd: 955_000, competitors: [{ bidder: "Metroplan International", priceUsd: 920_000 }, { bidder: "UrbanLink Africa", priceUsd: 975_000 }] }, checklist: [{ item: "Bid bond", complete: true }, { item: "Compliance documents", complete: true }, { item: "Technical methodology", complete: true }, { item: "CVs and commitment letters", complete: true }] },
  { id: "TND-2026-026", title: "Bishoftu Integrated Water Supply EOI", client: "Bishoftu Water Utility", clientType: "Public", consultancyType: "Design & Supervision", stage: "EOI", location: "Bishoftu", reference: "BWU/EOI/026/2026", valueUsd: 1_100_000, valueEtb: 152_900_000, deadline: "06 Aug 2026", deadlineDays: 13, probability: 35, dates: { preBid: "Not scheduled", siteVisit: "Not scheduled", technicalOpening: "06 Aug 2026", financialOpening: "Not applicable" }, personnel: [{ name: "Yared Abebe", role: "Proposed Team Lead", expertise: "Water Engineering", manMonths: 14 }], financial: { technicalWeight: 100, financialWeight: 0, ourPriceUsd: 0, competitors: [] }, checklist: [{ item: "Bid bond", complete: false }, { item: "Compliance documents", complete: true }, { item: "Technical methodology", complete: false }, { item: "CVs and commitment letters", complete: false }] },
  { id: "TND-2026-009", title: "Industrial Park Expansion PMC", client: "East Africa Development Fund", clientType: "Donor-Funded", consultancyType: "PMC", stage: "Awarded", location: "Dire Dawa", reference: "EADF/PMC/009/2026", valueUsd: 3_200_000, valueEtb: 444_800_000, deadline: "Awarded 12 Jul", deadlineDays: 0, probability: 100, dates: { preBid: "14 Apr 2026", siteVisit: "20 Apr 2026", technicalOpening: "12 May 2026", financialOpening: "26 May 2026" }, personnel: [{ name: "Mekdes Asfaw", role: "Proposed Team Lead", expertise: "PMC", manMonths: 28 }], financial: { technicalWeight: 80, financialWeight: 20, ourPriceUsd: 3_150_000, competitors: [{ bidder: "Global PMC Partners", priceUsd: 3_080_000 }] }, checklist: [{ item: "Bid bond", complete: true }, { item: "Compliance documents", complete: true }, { item: "Technical methodology", complete: true }, { item: "CVs and commitment letters", complete: true }] },
  { id: "TND-2026-004", title: "Private Mixed-Use Development Supervision", client: "Habesha Developments PLC", clientType: "Private", consultancyType: "Design & Supervision", stage: "Lost", location: "Addis Ababa", reference: "HDP/RFP/004/2026", valueUsd: 760_000, valueEtb: 105_640_000, deadline: "Closed 30 Jun", deadlineDays: 0, probability: 0, dates: { preBid: "10 May 2026", siteVisit: "13 May 2026", technicalOpening: "02 Jun 2026", financialOpening: "15 Jun 2026" }, personnel: [{ name: "Samuel Tadesse", role: "Proposed Team Lead", expertise: "Building Supervision", manMonths: 12 }], financial: { technicalWeight: 65, financialWeight: 35, ourPriceUsd: 745_000, competitors: [{ bidder: "UrbanWorks Consult", priceUsd: 710_000 }] }, checklist: [{ item: "Bid bond", complete: true }, { item: "Compliance documents", complete: true }, { item: "Technical methodology", complete: true }, { item: "CVs and commitment letters", complete: true }] },
];

export function filterTenders(query: string, clientType: ClientType | "All", consultancyType: ConsultancyType | "All"): Tender[] { const term = query.trim().toLowerCase(); return tenders.filter((tender) => (clientType === "All" || tender.clientType === clientType) && (consultancyType === "All" || tender.consultancyType === consultancyType) && (!term || [tender.title, tender.client, tender.reference, tender.location].join(" ").toLowerCase().includes(term))); }
export function formatTenderCurrency(value: number, currency: "USD" | "ETB") { return new Intl.NumberFormat("en-US", { style: "currency", currency, maximumFractionDigits: 0 }).format(value); }
export function getTenderMetrics() { const active = tenders.filter((tender) => !["Awarded", "Lost"].includes(tender.stage)); const closed = tenders.filter((tender) => ["Awarded", "Lost"].includes(tender.stage)); return { active: active.length, pipelineUsd: active.reduce((sum, tender) => sum + tender.valueUsd, 0), pipelineEtb: active.reduce((sum, tender) => sum + tender.valueEtb, 0), winRate: Math.round((tenders.filter((tender) => tender.stage === "Awarded").length / closed.length) * 100), upcoming: active.filter((tender) => tender.deadlineDays > 0 && tender.deadlineDays <= 14).length }; }
