"use client";

import { useState } from "react";
import type { VariationApproval, VariationOrder, VariationReason } from "@/lib/contractsData";

export function VariationModal({ contractTitle, onClose, onSave }: { contractTitle: string | null; onClose: () => void; onSave: (variation: Omit<VariationOrder, "id">) => void }) {
  const [title, setTitle] = useState(""); const [reason, setReason] = useState<VariationReason>("Scope Addition"); const [cost, setCost] = useState("0"); const [days, setDays] = useState("0"); const [status, setStatus] = useState<VariationApproval>("Draft");
  if (!contractTitle) return null;
  const submit = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const costImpactUsd = Number(cost); const timeImpactDays = Number(days); if (!title.trim() || !Number.isFinite(costImpactUsd) || !Number.isFinite(timeImpactDays)) return; onSave({ title: title.trim(), reason, costImpactUsd, timeImpactDays, status }); onClose(); };
  return <div className="fixed inset-0 z-[70] grid place-items-center p-4" role="dialog" aria-modal="true" aria-labelledby="variation-title"><button type="button" className="absolute inset-0 bg-slate-950/40" aria-label="Close variation modal" onClick={onClose} /><form onSubmit={submit} className="relative w-full max-w-xl rounded-xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-cyan-700">Variation order</p><h2 id="variation-title" className="mt-2 text-xl font-bold">Log variation request</h2><p className="mt-1 text-sm text-slate-500">{contractTitle}</p></div><button type="button" onClick={onClose} className="rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold">Close</button></div><div className="mt-6 grid gap-4"><label className="grid gap-1.5 text-sm font-semibold text-slate-700">VO title<input required value={title} onChange={(event) => setTitle(event.target.value)} className="rounded-lg border border-slate-300 px-3 py-2.5 font-normal outline-none focus:border-cyan-600" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1.5 text-sm font-semibold text-slate-700">Reason<select value={reason} onChange={(event) => setReason(event.target.value as VariationReason)} className="rounded-lg border border-slate-300 px-3 py-2.5 font-normal"><option>Scope Addition</option><option>Client Request</option><option>Unforeseen Site Condition</option></select></label><label className="grid gap-1.5 text-sm font-semibold text-slate-700">Approval status<select value={status} onChange={(event) => setStatus(event.target.value as VariationApproval)} className="rounded-lg border border-slate-300 px-3 py-2.5 font-normal"><option>Draft</option><option>Under Review</option><option>Approved</option><option>Rejected</option></select></label></div><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1.5 text-sm font-semibold text-slate-700">Cost impact (USD)<input type="number" step="0.01" value={cost} onChange={(event) => setCost(event.target.value)} className="rounded-lg border border-slate-300 px-3 py-2.5 font-normal" /></label><label className="grid gap-1.5 text-sm font-semibold text-slate-700">Time impact (days)<input type="number" step="1" value={days} onChange={(event) => setDays(event.target.value)} className="rounded-lg border border-slate-300 px-3 py-2.5 font-normal" /></label></div></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold">Cancel</button><button type="submit" className="rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white hover:bg-slate-700">Save variation</button></div></form></div>;
}
